name: schedule
description: "A new Flutter project."
publish_to: 'none'

version: 0.2.9+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  flutter_login:
    git:
        url: https://github.com/YiQiuYes/flutter_login.git
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  dynamic_color: ^1.7.0
  flutter_screenutil: ^5.9.3
  dio: ^5.6.0
  logger: ^2.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.4
  html: ^0.15.4
  shared_preferences: ^2.3.2
  flutter_picker_plus: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  flutter_expandable_fab: ^2.2.0
  qr_code_scanner: ^1.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/lotties/
    - lib/assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
